todoapp/urls.py
from django.urls import path, include
from . import views

app_name = 'todoapp' # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
    path('add_todo', views.add_todo, name='add_todo'),
    path('loginnav', views.index, name='loginnav'),
    path('delete_todo/<int:pk>/', views.delete_todo, name='delete_todo'),
    path('finished_task/<int:pk>/', views.finished_task, name='finished_task'),
    path('todo_display/', views.todo_display, name='todo_display'),

]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')) # Note: all your app urls will start with this path
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

todoapp/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from django.forms import ModelForm


class Todo(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.CharField(max_length=250, null=True, blank=True)
	finished = models.BooleanField(default=False)
	create_date = models.DateTimeField(default=datetime.now())

	def __str__(self):
		return self.body

todoapp/forms.py
from django.forms import ModelForm
from .models import Todo
from django import forms
from django.template import Template

class Todoform(forms.ModelForm):
	class Meta:
		model = Todo
		fields = ['body']

todoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpRequest
from .models import Todo
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms
from .forms import Todoform
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse

def index(request):
	if request.user.is_authenticated:
		todo_list = Todo.objects.filter(user=request.user)
	else :
		todo_list = []
	context = {'todo':todo_list}
	return render(request,'todoapp/index.html', context)

@login_required
def add_todo(request):
	if request.method == 'POST':
		todotext = request.POST.get('todo_text')
		newtodo = Todo(body=todotext, user=request.user)
		newtodo.save()
	return redirect('todoapp:index')

def todo_display(request):
	todo = Todo.objects.all()
	context = {'todo' :todo}
	return render(request,'lfw/todo_display.html', context)

@login_required
def delete_todo(request, pk):
	todo = get_object_or_404(Todo, pk=pk)
	todo.delete()
	return redirect('todoapp:index')
	
@login_required
def finished_task(request, pk):
	todo = get_object_or_404(Todo, pk=pk)
	todo.finished = not todo.finished
	todo.save()
	return redirect('todoapp:index')

todoapp/templates/todoapp/add_todo.html
{% load static %}

<form action="{% url 'todoapp:add_todo' %}" method="POST">
    {% csrf_token %}
    {{ form }}
	<input type="text" name="todo_text"/>

 <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
       
</form>

todoapp/templates/todoapp/base.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
 <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <title>
    {% block title %}{% endblock %}
  </title>
    {% block styles %}{% endblock styles %}
</head>

<body>


{% block content%}{% endblock %}

</body>

</html>

todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html' %}
{% load static %}
{% block title %}Todo{% endblock %}


{% block content%}
<h2>VERY EXCITING A TODOLIST</h2>
{%include "todoapp/loginnav.html" %}
{%include "todoapp/add_todo.html" %}
{%include "todoapp/todo_display.html" %}
{% endblock %}

todoapp/templates/todoapp/loginnav.html
	  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% endif %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>

  </ul>

todoapp/templates/todoapp/todo_display.html
{% extends 'todoapp/base.html' %}
{% load static %}
{% block styles%} 

{% endblock styles%}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% block content%}
<ul>
{% if user.is_authenticated %}      
    {% for task in todo %}
        <li>{{ task.body }}
        {{task.create_date}}
         	<a href="{% url 'todoapp:delete_todo' pk=task.id %}">
         <i class="material-icons">close</i>
         	</a>
         	
         	<a href="{% url 'todoapp:finished_task' pk=task.id %}">  
         	{% if task.finished%}
                <i class="material-icons">check_box</i>
         	{% else %}
                <i class="material-icons">check_box_outline_blank</i>
         	{% endif %}
         	</a>
        </li>
{% endfor %}
{% endif %}
</ul>

{% endblock %}